-- Inserir cards sem testimonials para demonstrar as opções alternativas
INSERT INTO cms_success_stories_cards (
  page_id,
  card_order,
  industry,
  company_name,
  challenge,
  solution,
  metric1_value,
  metric1_label,
  metric2_value,
  metric2_label,
  metric3_value,
  metric3_label,
  customer_quote,
  customer_name,
  customer_title,
  image_url,
  language
) VALUES
(
  '02b3edf8-22fe-4553-99ae-45c8127f2ea7',
  10,
  'FinTech',
  'BankTech Solutions',
  'Processos manuais de aprovação de crédito causavam demora e perda de clientes potenciais.',
  'Implementamos sistema de análise de crédito automatizado com IA para aprovação em tempo real.',
  '+75%',
  'Aprovações Rápidas',
  '-50%',
  'Tempo de Processo',
  '+200%',
  'Conversão',
  '',
  '',
  '',
  'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=200&fit=crop&auto=format',
  'pt'
),
(
  '02b3edf8-22fe-4553-99ae-45c8127f2ea7',
  11,
  'Healthcare',
  'MedConnect',
  'Gestão ineficiente de inventário médico resultava em desperdício e falta de insumos críticos.',
  'Desenvolvemos plataforma de gestão inteligente com previsão de demanda baseada em IA.',
  '+90%',
  'Precisão Estoque',
  '-40%',
  'Desperdício',
  '+150%',
  'Eficiência',
  '',
  '',
  '',
  'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=400&h=200&fit=crop&auto=format',
  'pt'
),
(
  '02b3edf8-22fe-4553-99ae-45c8127f2ea7',
  12,
  'Manufacturing',
  'AutoParts Pro',
  'Falhas de equipamento não previstas causavam paradas custosas na linha de produção.',
  'Implementamos sistema de manutenção preditiva com sensores IoT e análise de dados em tempo real.',
  '+95%',
  'Previsão Falhas',
  '-65%',
  'Tempo Parado',
  '+180%',
  'Produtividade',
  '',
  '',
  '',
  'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=200&fit=crop&auto=format',
  'pt'
);