// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwhxacuxkwbdptyjwgds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3aHhhY3V4a3diZHB0eWp3Z2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjAyMTUsImV4cCI6MjA2NjYzNjIxNX0.BdWVpSkdeDvXbRJ0bL8g0inAnceBHIz8e0WZeoi4sWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);